# Generated by Django 3.1.7 on 2021-03-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yearRange', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('total_number', models.FloatField()),
            ],
            options={
                'verbose_name': 'Ranking',
                'db_table': 'Ranking',
            },
        ),
    ]
